### ISSUE TITLE
pdf2write.sh generates blank pages on Mac OS

### ISSUE THREAD

**Issue by AndreaCallia** [styluslabs/templates#1]
Hi all,

as said in the subject, I tried to use the `pdf2write.sh` script that you suggest to write on PDFs (also thanks for suggesting the alternative software in the FAQ, but still I wanted to try), it seems to partially work because it recognizes the PDF file and it generates a number of pages equal to the original file, but the problem is that the pages are completely empty.

Perhaps this script was not tested in Mac OS? or perhaps some of the engines/tools used by the script do not work on Mac OS? Perhaps it would work if I select some specific options (like the image format, resolution, etc.)?

Unfortunately I cannot give you more information so far because apparently the script does not print any error message, it behaves as everything has been done correctly, but the PDF pages are empty.

Many thanks for your great work and your great tool, from a MacOS user with an external tablet/dispay with a stylus...

**UPDATE:** I looked inside the generated SVGZ file, and it seems there are actually several `<image>` tags (as many as the number of PDF pages) with some base64-encoded data inside (are the newline characters supposed to be there?), but they appear blank when I open the file. I paste one of the `<image>` tags partially here:

```
<image x="0" y="0" width="1239" height="1754" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACa8AAA20CAQAAABSEOvjAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAA
ASwAAAEsAHOI6VIAAAAHdElNRQfkBg0NKR/9vd8EAAAKeHpUWHRSYXcgcHJvZmlsZSB0eXBlIGlj
YwAAWIWdl22SZKkNRf+zCi+BTwktBwSK8P434ENWd0+33TNjOyuIzHoPhJCu7hXpn+7pH3zqUEn5
...
VDExOjQxOjMxKzAyOjAwol32wwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wNi0xM1QxMTo0MToz
MSswMjowMNMATn8AAAAmdEVYdHBkZjpIaVJlc0JvdW5kaW5nQm94ADU5NC45Nng4NDIuMDQrMCsw
7wuGawAAABR0RVh0cGRmOlZlcnNpb24AUERGLTEuMyBTBqy/AAAAAElFTkSuQmCC
"/>

```

**Comment by AndreaCallia** [comment]
Hi all,

as said in the subject, I tried to use the `pdf2write.sh` script that you suggest to write on PDFs (also thanks for suggesting the alternative software in the FAQ, but still I wanted to try), it seems to partially work because it recognizes the PDF file and it generates a number of pages equal to the original file, but the problem is that the pages are completely empty.

Perhaps this script was not tested in Mac OS? or perhaps some of the engines/tools used by the script do not work on Mac OS? Perhaps it would work if I select some specific options (like the image format, resolution, etc.)?

Unfortunately I cannot give you more information so far because apparently the script does not print any error message, it behaves as everything has been done correctly, but the PDF pages are empty.

Many thanks for your great work and your great tool, from a MacOS user with an external tablet/dispay with a stylus...

**UPDATE:** I looked inside the generated SVGZ file, and it seems there is actually an `<image>` tag with some data inside (are the newline characters assumed to be there?), I paste it partially here:

<image x="0" y="0" width="1239" height="1754" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACa8AAA20CAQAAABSEOvjAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAA
ASwAAAEsAHOI6VIAAAAHdElNRQfkBg0NKR/9vd8EAAAKeHpUWHRSYXcgcHJvZmlsZSB0eXBlIGlj
YwAAWIWdl22SZKkNRf+zCi+BTwktBwSK8P434ENWd0+33TNjOyuIzHoPhJCu7hXpn+7pH3zqUEn5
...
VDExOjQxOjMxKzAyOjAwol32wwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wNi0xM1QxMTo0MToz
MSswMjowMNMATn8AAAAmdEVYdHBkZjpIaVJlc0JvdW5kaW5nQm94ADU5NC45Nng4NDIuMDQrMCsw
7wuGawAAABR0RVh0cGRmOlZlcnNpb24AUERGLTEuMyBTBqy/AAAAAElFTkSuQmCC
"/>

**Comment by AndreaCallia** [comment]
Another update: if I comment the `rm` command in the script to keep the temporary PNG images instead of removing them at the end of the script, then the tool let me insert them in the blank page manually one by one (also I need to adjust them manually to fit the size of the page), and if I save the file and I reopen it, the images added manually appear. Therefore inserting an image in the tool works on MacOS as well, then there must be some problem in the way the SVGZ file is generated by the script.

**Comment by AndreaCallia** [comment]
Further important update: I tried to use a modified version of [this script](https://edward-kim-math.github.io/resources/pdf2write.html) to make an SVG file using a different script, and the images are auto-generated correctly and they appear in the Write tool when I open the file, so I think it is definitely some issue in your script, I will keep working to understand if I can fix it by myself.

**Comment by AndreaCallia** [comment]
Further update: I tried to use the modification of the alternative script mentioned in the previous comment to generate an SVG file, where Write says it's not generated using Write (but it still shows the image), and I left the `<image>` tag, including the BASE64 data, but I replaced the rest of the SVG metadata with the metadata coming from your `pdf2write.sh` script. Now it works! And the SVGZ file is recognized as a file created using Write, so the format is perfect and the images from the PDF are shown...

Then this means that the problem is the way you invoke the `convert` tool to generate the BASE64 data (which is invoked also by the alternative script), or the way you paste the BASE64 data in the SGVZ file. Hopefully I will manage to solve the mistery...

**Comment by AndreaCallia** [comment]
Solved it!

I think I understood that the only issue in your script (at least under MacOS) is the way you generate the BASE64 encoding of the image using the `base64` shell tool, therefore I made a different version of your script, but I wrote in Python instead of bash, by taking some code from the file that I linked before in another comment, where the `base64` encoding is generated using Python libraries instead.

The resulting Python script is attached below. It works perfectly here, but I didn't double checked it for correctness and also there is no error handling, therefore I am not sure of what happens if you specify, for example, a wrong filename in input, or if it cannot create the files for some reasons, etc.

Also, in the script I use the `eval` function to quickly get the width and height values from a shell tool in Python, and I know this is bad practice in terms of security, because `eval` can evaluate any Python instruction, and I should have used a more specific way of parsing width and height values.

Therefore, use this script at your own risk. Since this makes PDF annotation working under MacOS, it would be good for you to take my script, check it for correctness and security, and integrate it in the repository, because it can help many people wishing to annotate PDFs using Write under MacOS.

The script is attached below. Remember that it is a rewriting of your script in Python, with some code taken from [this script](https://edward-kim-math.github.io/resources/pdf2write.html), therefore you will see a lot of similar or identical code compared to those two scripts.

```
#!/usr/local/bin/python2
# Create a Write document from a PDF by generating page images

import sys
import os
import glob
import base64

print "Converting PDF to images..."

os.system('convert -density 300 -scene 1 ' + sys.argv[1] +' out-%03d.png')

SVGOUTname = sys.argv[1][:-4] + '.svg'
SVGOUT = open(SVGOUTname, 'w')
print "Generating Write document..."

print >>SVGOUT, '<svg id="write-document" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'
print >>SVGOUT, '<rect id="write-doc-background" width="100%" height="100%" fill="#808080"/>'

filenames = sorted(glob.glob('out-*.png'))

for PNGPAGE in filenames:
  filehandle = open(PNGPAGE,'rb') # read binary
  filecontent = filehandle.read()
  encoded = base64.standard_b64encode(filecontent).decode('ascii')
  filehandle.close()
  (WIDTH2, HEIGHT2) = eval(os.popen('identify -format "(%w, %h)" ' + PNGPAGE).read())
  WIDTH = WIDTH2 / 2
  HEIGHT = HEIGHT2 / 2
  print >>SVGOUT, '<svg class="write-page" color-interpolation="linearRGB" x="10" y="10" width="%dpx" height="%dpx" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">' % (WIDTH, HEIGHT)
  print >>SVGOUT, '  <g class="write-content write-v3" xruling="0" yruling="40" marginLeft="100" papercolor="#FFFFFF" rulecolor="#9F0000FF">'
  print >>SVGOUT, '    <g class="ruleline write-no-dup" shape-rendering="crispEdges">'
  print >>SVGOUT, '      <rect class="pagerect" fill="#FFFFFF" stroke="none" x="0" y="0" width="%d" height="%d" />' % (WIDTH, HEIGHT)
  SVGOUT.write('      <image x="0" y="0" width="%d" height="%d" xlink:href="data:image/png;base64,' % (WIDTH, HEIGHT))
  SVGOUT.write(encoded)
  SVGOUT.write('"/>\n    </g>\n  </g>\n</svg>')
  
SVGOUT.write('\n</svg>')

SVGOUT.close()

os.system('gzip -S z ' + SVGOUTname)

os.system('rm out-*.png')

print 'Finished creating ' + SVGOUTname + 'z'

```

**Comment by AndreaCallia** [comment]
And found the solution with your script as well! :)

After understanding that the problem was with the `base64` tool that you use to generate the BASE64 encoding, I realized that an important difference between the encoding generated using that tool and the encoding generated using the Python libraries was that the `base64` tool, at least under MacOS, always puts a line break every 76 characters, which disrupts the output file.

Therefore, I tried to write `base64 --help` and I have found this.

```
  -w, --wrap=COLS       wrap encoded lines after COLS character (default 76).
                          Use 0 to disable line wrapping
```

Therefore, I just replaced in your original script the code `base64 $PNGPAGE >> $SVGOUT` (line 31) with `base64 -w 0 $PNGPAGE >> $SVGOUT` and your script worked as well! If I only understood earlier I would have saved the effort of rewriting it in Python, but I still enjoyed it somehow. 🙂

Therefore now I can attach a Bash script which works under MacOS and which is just as safe as yours, since it is obtained by just slightly modifying your script with the replacement above. I suggest that you add this script to the repository as an alternative script to yours for MacOS, or that you modify your script to make it detect whether it is executed under MacOS, to add the `-w 0` option to `base64` if needed.

The script patched by me is attached.

```
#!/bin/bash
# Create a Write document from a PDF by generating page images

echo "Converting PDF to images..."
(command -v pdftoppm >/dev/null 2>&1 && pdftoppm -png -r 300 $1 out) || convert -density 300 -scene 1 $1 out-%03d.png
if [ ! -f "out-1.png" ] && [ ! -f "out-01.png" ] && [ ! -f "out-001.png" ]; then
  echo "No page images found: make sure pdftoppm (from poppler-utils) or imagemagick and ghostscript are installed"
  exit 1
  
fi
SVGOUT=$(basename $1 pdf)svg
echo "Generating Write document..."

printf '<svg id="write-document" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n' > $SVGOUT
printf '<rect id="write-doc-background" width="100%%" height="100%%" fill="#808080"/>\n' >> $SVGOUT

for PNGPAGE in out-*.png
do
  read WIDTH2 HEIGHT2 < <(identify -format "%w %h" $PNGPAGE)
  # page images generated at 300 DPI but Write uses 150 DPI as reference
  WIDTH=$((WIDTH2/2))
  HEIGHT=$((HEIGHT2/2))

  printf '<svg class="write-page" color-interpolation="linearRGB" x="10" y="10" width="%dpx" height="%dpx" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n' $WIDTH $HEIGHT >> $SVGOUT
  printf '  <g class="write-content write-v3" xruling="0" yruling="40" marginLeft="100" papercolor="#FFFFFF" rulecolor="#9F0000FF">\n' >> $SVGOUT
  printf '    <g class="ruleline write-no-dup" shape-rendering="crispEdges">\n' >> $SVGOUT
  printf '      <rect class="pagerect" fill="#FFFFFF" stroke="none" x="0" y="0" width="%d" height="%d" />\n' $WIDTH $HEIGHT >> $SVGOUT

  printf '      <image x="0" y="0" width="%d" height="%d" xlink:href="data:image/png;base64,' $WIDTH $HEIGHT >> $SVGOUT
  # doesn't seem to be a way to prevent base64 from appending newline
  base64 -w 0 $PNGPAGE >> $SVGOUT
  printf '"/>\n    </g>\n  </g>\n</svg>' >> $SVGOUT
done

printf "\n</svg>" >> $SVGOUT

gzip -S z $SVGOUT
rm out-*.png
echo "Finished creating $SVGOUT"z

```

**Comment by AndreaCallia** [comment]
And finally I have found an OS-independent solution!

since apparently options and default values related to line breaks for the `base64` command are different under different OS's (e.g. Linux vs Mac OS), the n instead of using the `base64` options I just decided to _delete_ the line breaks from the `base64` output using the `tr` command, which works the same in every OS. More precisely,  I replaced in your original script the `code base64 $PNGPAGE >> $SVGOUT` (line 31) with `base64 $PNGPAGE | tr -d '\n' >> $SVGOUT`.

Therefore this works under any OS, and I suggest that you make the same little change to your `pdf2write.sh` script.

I attach my resulting `pdf2write.sh` script below.

```
#!/bin/bash
# Create a Write document from a PDF by generating page images

echo "Converting PDF to images..."
(command -v pdftoppm >/dev/null 2>&1 && pdftoppm -png -r 300 $1 out) || convert -density 300 -scene 1 $1 out-%03d.png
if [ ! -f "out-1.png" ] && [ ! -f "out-01.png" ] && [ ! -f "out-001.png" ]; then
  echo "No page images found: make sure pdftoppm (from poppler-utils) or imagemagick and ghostscript are installed"
  exit 1
  
fi
SVGOUT=$(basename $1 pdf)svg
echo "Generating Write document..."

printf '<svg id="write-document" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n' > $SVGOUT
printf '<rect id="write-doc-background" width="100%%" height="100%%" fill="#808080"/>\n' >> $SVGOUT

for PNGPAGE in out-*.png
do
  read WIDTH2 HEIGHT2 < <(identify -format "%w %h" $PNGPAGE)
  # page images generated at 300 DPI but Write uses 150 DPI as reference
  WIDTH=$((WIDTH2/2))
  HEIGHT=$((HEIGHT2/2))

  printf '<svg class="write-page" color-interpolation="linearRGB" x="10" y="10" width="%dpx" height="%dpx" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n' $WIDTH $HEIGHT >> $SVGOUT
  printf '  <g class="write-content write-v3" xruling="0" yruling="40" marginLeft="100" papercolor="#FFFFFF" rulecolor="#9F0000FF">\n' >> $SVGOUT
  printf '    <g class="ruleline write-no-dup" shape-rendering="crispEdges">\n' >> $SVGOUT
  printf '      <rect class="pagerect" fill="#FFFFFF" stroke="none" x="0" y="0" width="%d" height="%d" />\n' $WIDTH $HEIGHT >> $SVGOUT

  printf '      <image x="0" y="0" width="%d" height="%d" xlink:href="data:image/png;base64,' $WIDTH $HEIGHT >> $SVGOUT
  # doesn't seem to be a way to prevent base64 from appending newline
  # base64 -w 0 $PNGPAGE | tr -d >> $SVGOUT
  base64 $PNGPAGE | tr -d '\n' >> $SVGOUT
  printf '"/>\n    </g>\n  </g>\n</svg>' >> $SVGOUT
done

printf "\n</svg>" >> $SVGOUT

gzip -S z $SVGOUT
rm out-*.png
echo "Finished creating $SVGOUT"z

```

**Comment by rbbernardino** [comment]
wow! That's pretty impressive, great work!! Thank you very much for that, I have just discovered this tool, as I have just bought my first graphic tablet. Thank you so much for that!!!

Don't you think you could just fork it, commit and make a pull request? So hopefully the owners will accept it?

**Comment by AndreaCallia** [comment]
Many thanks for this @rbbernardino , I would do it but I am quite overwhelmed with my own deadlines, but I still wanted to contribute by putting the code here :) please feel free to do this if you want, otherwise I will try to do this in the future, if I will happen to finally have some more free time :)

**Comment by styluslabs** [comment]
Apologies, I didn't have notifications turned on for this repo!  The underlying problem is that Write fails to handle whitespace in base64 encoded strings - I will fix that shortly.

**Comment by AndreaCallia** [comment]
Many thanks @styluslabs for your reply, my change in your script should work as a workaround, you could consider just using it, or if you want to handle whitespaces then even better :)

**Comment by styluslabs** [comment]
Yes, thank you very much - I've updated the script with your fix
