### ISSUE TITLE
pdf2write.sh loses bar lines when converting from pdf to svgz

### ISSUE THREAD

**Issue by Jaydon-chai** [styluslabs/templates#10]
[document.pdf](https://github.com/styluslabs/templates/files/6463520/document.pdf)

[Clair de Lune.zip](https://github.com/styluslabs/templates/files/6463522/Clair.de.Lune.zip)

I've zipped to svgz since github didn't allow uploads of that.

What changes may I make to pdf2write to prevent the loss of those thin bar lines like in page 5?

Many thanks for your time, apologies for the poor formatting of issue, i am new to github

**Comment by styluslabs** [comment]
I have updated pdf2write with a "--vector" option which seems to produce
good results with your document.
