### ISSUE TITLE
How to use pdf2write.sh ?

### ISSUE THREAD

**Issue by pmaen** [styluslabs/templates#2]
I'm somewhat new to al this so how do I make this script actually convert a pdf to png? If I run it nothing much happens nor can i specify a file.
If I run it in terminal I get
`Converting PDF to images...`
`I/O Error: Couldn't open file 'out': No such file or directory.`
`convert-im6.q16: no images defined 'out-%03d.png' @ error/convert.c/ConvertImageCommand/3258.`
`No page images found: make sure pdftoppm (from poppler-utils) or imagemagick and ghostscript are installed`

**Comment by vszabo2** [comment]
You need to put the name (and path) of the pdf file after the name of the script on the command line.
For example, `./pdf2write.sh input-file.pdf` if input-file.pdf is in the current directory.
